# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-9a51cd23-f36f-4d15-b10c-79b4522803c3";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-9a51cd23-f36f-4d15-b10c-79b4522803c3".device = "/dev/disk/by-uuid/9a51cd23-f36f-4d15-b10c-79b4522803c3";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B4CB-FAFC";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/cd0099db-7d16-49d0-a988-54eb3d04a9b5"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
