[default_session]
startup_command = 'tmux rename-window editor && nvim'

[[session]]
name='Downloads ' 
path='~/Downloads'
startup_command='ls'

[[session]]
name='Nixos Config '
path='~/.config/nvim/'

[[session]]
name="Home Manager Config "
path="~/nixos/home/"

[[session]]
name="Harro Docs "
path='~/Harro-docs/'
